### ISSUE TITLE
Header & footer support

### ISSUE THREAD

**Issue by phildionne** [MikaelMayer/Sketch-n-Script#5]
When testing with a Google Docs document including a header and a footer including a variable and/or a formula, clicking on _Display values_ doesn't "evaluate" variables nor formulas.

The expected behavior would be for variables and formulas in both header and footer to be "evaluated".

**Comment by MikaelMayer** [comment]
Nice finding! I did not know about Google docs support for header and footers.
Feature implemented in commit https://github.com/MikaelMayer/Sketch-n-Script/commit/2d7c89ada941459c38869d89745c03d82e31cf1d and submitted as the next plug-in version to Google docs (along with some other bug fixes)

**Comment by phildionne** [comment]
Awesome, thank you!
