### ISSUE TITLE
=email[Evaluation error: ReferenceError: L'élément "email" n'est pas défini.] 

### ISSUE THREAD

**Issue by webstream10** [MikaelMayer/Sketch-n-Script#6]
When I try to apply a variable over a formated text then the plugin I see this error:

=email[Evaluation error: ReferenceError: L'élément "email" n'est pas défini.] 

Thanks your much for your work, I really appreciate it.
It is a great addon

**Comment by MikaelMayer** [comment]
Great to hear that you like it.
Where and how did you define the variable email?

I would assume you would have something like this in your document:

    emailme = ["email me.",{link: "mailto:your@email.com}]

    If you have any question, please =emailme

Which should work perfectly.
Can you give me a way to reproduce the problem?

Le ven. 12 juil. 2019 à 09:37, webstream10 <notifications@github.com> a
écrit :
