### ISSUE TITLE
Generic Error when clicking "Display Values"

### ISSUE THREAD

**Issue by fernandorych** [MikaelMayer/Sketch-n-Script#7]
Error while computing last '=PLG4EEtEqdX0zVOjjXbeC7lcJkVNW0nn8E[Evaluation error: ReferenceError: L'élément "PLG4EEtEqdX0zVOjjXbeC7lcJkVNW0nn8E" n'est pas défini.]', SyntaxError: Signe ] manquant dans l'expression d'index.

**Comment by MikaelMayer** [comment]
Could you please submit an minimum reproducing example?

Le jeu. 17 oct. 2019 à 23:42, fernandorych <notifications@github.com> a
écrit :

**Comment by MikaelMayer** [comment]
Oh I see now. If you have the sign = in your document followed by letters, it will think it's a formula.
To avoid the = be interpreted as a formula, you need to escape it, e.g. =("=")
